version: 0.1

phases:
  install:
    commands:
      - echo Insatlling NPM Packages and wget Enviorment File
      - npm install 
      - npm install babel-cli cross-env --global
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - npm run start 
artifacts:
  discard-paths: yes
